package dev.noctud.latte.config;

import com.intellij.testFramework.fixtures.BasePlatformTestCase;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Every filter and tag the reference tables list has to be one the plugin knows.
 *
 * The tables under {@code docs/latte/} are generated by reading Latte's own registration code at
 * each tag, so they are the closest thing to the language that exists inside this repository. What
 * they and the registry disagree about is a report the plugin makes on a template that is correct -
 * "Undefined latte filter" on a filter that has always existed - and until this test there was
 * nothing that would notice: a missing registration looks exactly like a filter the project made up
 * itself.
 *
 * The tables are also what a per-version registry will be built from, so their agreement with the
 * registry has to be established first. A version filter over an incomplete set would narrow
 * something that is already too small.
 *
 * Only names are read. Nothing here touches a template outside this repository.
 */
public class ReferenceTablesCoverageTest extends BasePlatformTestCase {

    private static final Path FILTERS = Paths.get("docs/latte/reference-filters.md");
    private static final Path TAGS = Paths.get("docs/latte/reference-tags.md");

    /**
     * A table row starts with the item in backticks, and the three columns after it say whether it
     * exists in 2.11, 3.0 and 3.1 - "yes", "no", or the patch it arrived in. Anything else in the
     * file is prose.
     */
    private static final Pattern ROW = Pattern.compile("^\\|\\s*`([^`]+)`\\s*\\|(.*)$");

    /** "yes", "no", or the patch an item arrived in - what a version column may say and nothing else. */
    private static final Pattern VERSION_COLUMN = Pattern.compile("yes|no|\\d+\\.\\d+(\\.\\d+)?");

    public void testEveryFilterInTheReferenceTableIsRegistered() throws IOException {
        List<String> missing = new ArrayList<>();
        for (String filter : namesIn(FILTERS)) {
            if (LatteConfiguration.getInstance(getProject()).getFilter(filter) == null) {
                missing.add(filter);
            }
        }
        assertEquals("Filters the reference table lists and the registry does not know."
            + " Each one is an \"Undefined latte filter\" on a template that is correct.",
            List.of(), missing);
    }

    public void testEveryTagInTheReferenceTableIsRegistered() throws IOException {
        List<String> missing = new ArrayList<>();
        for (String tag : namesIn(TAGS)) {
            // The same file carries a second table listing what {syntax} accepts - "off", "double".
            // Those are arguments, not tags, and only a row written as {tag} or n:attr is one.
            if (!tag.startsWith("{") && !tag.startsWith("n:")) {
                continue;
            }
            String name = tag.replaceAll("^\\{/?", "").replaceAll("}$", "").replaceAll("^n:", "");
            if (name.isEmpty()) {
                continue;
            }
            if (LatteConfiguration.getInstance(getProject()).getTag(name) == null) {
                missing.add(name);
            }
        }
        assertEquals("Tags the reference table lists and the registry does not know."
            + " Each one is an \"Unknown tag\" on a template that is correct.",
            List.of(), missing);
    }

    /**
     * The names the table says exist in at least one supported line.
     *
     * A row that is "no" in all three is there for history - {@code &#123;?&#125;} was removed in
     * 2.11.0 and is listed only because 2.10 templates still hold it - and requiring the registry
     * to carry it would be asking the plugin to know a language it does not support.
     *
     * The table itself is the source; a list written here would be a second one, and they drift.
     */
    private static List<String> namesIn(Path table) throws IOException {
        assertTrue("Missing " + table.toAbsolutePath(), Files.isRegularFile(table));
        List<String> names = new ArrayList<>();
        int rows = 0;
        for (String line : Files.readAllLines(table, StandardCharsets.UTF_8)) {
            Matcher matcher = ROW.matcher(line);
            if (!matcher.find()) {
                continue;
            }
            rows++;
            if (existsInAnySupportedLine(matcher.group(2))) {
                names.add(matcher.group(1));
            }
        }
        assertFalse("No rows were read from " + table + " - the table's shape changed", rows == 0);
        assertFalse("No supported item was read from " + table, names.isEmpty());
        return names;
    }

    /**
     * Whether the row says the item exists in a line the plugin supports.
     *
     * The same file holds two tables of different shapes: Latte's own filters carry three version
     * columns, and the ones nette/application adds carry a source instead. A row is read as
     * version-stamped only when its first three columns all say what a version column may say -
     * otherwise it has no version to go by and is required unconditionally, which is right for a
     * filter that a package ships whatever the Latte line is.
     *
     * Written the other way round - "skip the row when it does not look version-stamped" - this
     * check silently dropped the nette/application table and turned two genuinely missing filters
     * into a passing test.
     */
    private static boolean existsInAnySupportedLine(String rest) {
        String[] columns = rest.split("\\|", -1);
        if (columns.length < 3) {
            return true;
        }
        for (int i = 0; i < 3; i++) {
            if (!VERSION_COLUMN.matcher(columns[i].trim()).matches()) {
                return true;
            }
        }
        for (int i = 0; i < 3; i++) {
            if (!"no".equals(columns[i].trim())) {
                return true;
            }
        }
        return false;
    }
}
